import "server-only";
import { db, serverTimestamp, hasAdminConfig } from "@/lib/firebase-admin.js";
import { parseList, randomCode, randomToken, toISO } from "@/lib/utils.js";

function safeDb() {
  if (!hasAdminConfig()) throw new Error("Firebase admin config missing");
  return db();
}
function productFromDoc(doc) {
  const data = doc.data() || {};
  return { id: doc.id, title: data.title || "", slug: data.slug || "", description: data.description || "", category: data.category || "Khác", price: Number(data.price || 0), oldPrice: data.oldPrice ? Number(data.oldPrice) : null, imageUrl: data.imageUrl || "", imagePublicId: data.imagePublicId || null, fileUrl: data.fileUrl || "", filePublicId: data.filePublicId || null, featured: Boolean(data.featured), visible: data.visible !== false, tags: Array.isArray(data.tags) ? data.tags : [], createdAt: toISO(data.createdAt), updatedAt: toISO(data.updatedAt) };
}
function couponFromDoc(doc) {
  const data = doc.data() || {};
  return { id: doc.id, code: String(data.code || "").toUpperCase(), type: data.type === "fixed" ? "fixed" : "percent", value: Number(data.value || 0), active: data.active !== false, maxUses: data.maxUses ?? null, usedCount: Number(data.usedCount || 0), expiresAt: toISO(data.expiresAt) || null };
}
function orderFromDoc(doc) {
  const data = doc.data() || {};
  return { id: doc.id, code: data.code || "", customerName: data.customerName || "", email: data.email || "", phone: data.phone || "", note: data.note || "", items: Array.isArray(data.items) ? data.items : [], subtotal: Number(data.subtotal || 0), discount: Number(data.discount || 0), total: Number(data.total || 0), status: data.status || "pending", couponCode: data.couponCode || null, downloadToken: data.downloadToken || "", createdAt: toISO(data.createdAt), paidAt: toISO(data.paidAt) || null, transferContent: data.transferContent || "" };
}
export async function listPublicProducts() { try { const snap = await safeDb().collection("products").orderBy("createdAt","desc").get(); return snap.docs.map(productFromDoc).filter((p) => p.visible !== false); } catch { return []; } }
export async function listAllProducts() { try { const snap = await safeDb().collection("products").orderBy("createdAt","desc").get(); return snap.docs.map(productFromDoc); } catch { return []; } }
export async function getProductBySlug(slug) { try { const snap = await safeDb().collection("products").where("slug","==",slug).limit(1).get(); return snap.empty ? null : productFromDoc(snap.docs[0]); } catch { return null; } }
export async function getProductById(id) { try { const doc = await safeDb().collection("products").doc(id).get(); return doc.exists ? productFromDoc(doc) : null; } catch { return null; } }
export async function upsertProduct(input) { const ref = input.id ? safeDb().collection("products").doc(input.id) : safeDb().collection("products").doc(); const snap = await ref.get(); const now = serverTimestamp(); await ref.set({ title: input.title, slug: input.slug, description: input.description, category: input.category, price: Number(input.price || 0), oldPrice: input.oldPrice ?? null, imageUrl: input.imageUrl, imagePublicId: input.imagePublicId ?? null, fileUrl: input.fileUrl, filePublicId: input.filePublicId ?? null, featured: Boolean(input.featured), visible: input.visible !== false, tags: input.tags || [], updatedAt: now, createdAt: snap.exists ? (snap.data() || {}).createdAt || now : now }, { merge: true }); return getProductById(ref.id); }
export async function deleteProduct(id) { await safeDb().collection("products").doc(id).delete(); }
export async function listCoupons() { try { const snap = await safeDb().collection("coupons").orderBy("createdAt","desc").get(); return snap.docs.map(couponFromDoc); } catch { return []; } }
export async function getCouponByCode(code) { try { const snap = await safeDb().collection("coupons").where("code","==",String(code || "").toUpperCase()).limit(1).get(); return snap.empty ? null : couponFromDoc(snap.docs[0]); } catch { return null; } }
export function applyCouponToAmount(coupon, subtotal) { if (!coupon || !coupon.active) return 0; if (coupon.expiresAt && new Date(coupon.expiresAt).getTime() < Date.now()) return 0; if (coupon.maxUses !== null && coupon.usedCount >= coupon.maxUses) return 0; if (coupon.type === "fixed") return Math.min(subtotal, Math.max(0, coupon.value)); return Math.min(subtotal, Math.round((subtotal * coupon.value) / 100)); }
export async function upsertCoupon(input) { const ref = input.id ? safeDb().collection("coupons").doc(input.id) : safeDb().collection("coupons").doc(); const snap = await ref.get(); const now = serverTimestamp(); await ref.set({ code: String(input.code || "").toUpperCase(), type: input.type, value: Number(input.value || 0), active: Boolean(input.active), maxUses: input.maxUses ?? null, usedCount: Number(input.usedCount || 0), expiresAt: input.expiresAt || null, updatedAt: now, createdAt: snap.exists ? (snap.data() || {}).createdAt || now : now }, { merge: true }); return getCouponByCode(input.code); }
export async function deleteCoupon(id) { await safeDb().collection("coupons").doc(id).delete(); }
export async function createOrder(input) { const subtotal = input.items.reduce((sum, item) => sum + item.price * item.quantity, 0); const coupon = input.couponCode ? await getCouponByCode(input.couponCode) : null; const discount = applyCouponToAmount(coupon, subtotal); const total = Math.max(0, subtotal - discount); const ref = safeDb().collection("orders").doc(); const code = randomCode("OD"); const downloadToken = randomToken(28); await ref.set({ code, customerName: input.customerName.trim(), email: input.email.trim(), phone: input.phone.trim(), note: input.note?.trim() || "", items: input.items, subtotal, discount, total, status: "pending", couponCode: coupon?.code || input.couponCode?.toUpperCase() || null, downloadToken, createdAt: serverTimestamp(), paidAt: null, transferContent: code }); return getOrderById(ref.id); }
export async function listOrders() { try { const snap = await safeDb().collection("orders").orderBy("createdAt","desc").get(); return snap.docs.map(orderFromDoc); } catch { return []; } }
export async function getOrderById(id) { try { const doc = await safeDb().collection("orders").doc(id).get(); return doc.exists ? orderFromDoc(doc) : null; } catch { return null; } }
export async function getOrderByCode(code) { try { const snap = await safeDb().collection("orders").where("code","==",code).limit(1).get(); return snap.empty ? null : orderFromDoc(snap.docs[0]); } catch { return null; } }
export async function updateOrder(id, patch) { const ref = safeDb().collection("orders").doc(id); const current = await ref.get(); if (!current.exists) return null; const data = current.data() || {}; await ref.set({ ...patch, paidAt: patch.status === "paid" ? serverTimestamp() : data.paidAt || null, updatedAt: serverTimestamp() }, { merge: true }); return getOrderById(id); }
export async function markOrderPaidByCode(code, payload = null) { const order = await getOrderByCode(code); if (!order) return null; await safeDb().collection("orders").doc(order.id).set({ status: "paid", paidAt: serverTimestamp(), updatedAt: serverTimestamp(), webhookPayload: payload }, { merge: true }); return getOrderById(order.id); }
export async function upsertUserProfile(profile) { if (!profile?.uid) return null; const ref = safeDb().collection("users").doc(profile.uid); const snap = await ref.get(); await ref.set({ uid: profile.uid, email: profile.email || null, name: profile.name || null, photoURL: profile.photoURL || null, role: snap.exists ? (snap.data() || {}).role || "user" : "user", lastLoginAt: serverTimestamp(), updatedAt: serverTimestamp() }, { merge: true }); const doc = await ref.get(); return doc.exists ? doc.data() : null; }
export async function getUserProfile(uid) { try { const doc = await safeDb().collection("users").doc(uid).get(); return doc.exists ? doc.data() : null; } catch { return null; } }
export async function getDashboardStats() { const [products, orders, coupons] = await Promise.all([listAllProducts(), listOrders(), listCoupons()]); const revenue = orders.filter((o) => o.status === "paid" || o.status === "delivered").reduce((sum, o) => sum + (o.total || 0), 0); return { products: products.length, orders: orders.length, coupons: coupons.length, revenue }; }
